### PR TITLE
Updated to safe 1.4.1

### PR DESCRIPTION
**Pull request by 0xKitsune**
I updated the submodule for the `safe-contracts` submodule from v1.3.0 to v1.4.1. 

The [`createProxy()`](https://github.com/safe-global/safe-contracts/blob/767ef36bba88bdbc0c9fe3708a4290cabef4c376/contracts/proxies/GnosisSafeProxyFactory.sol#L15) function seems to have been removed so I replaced it with the [`createProxyWithNonce()`](https://github.com/safe-global/safe-contracts/blob/main/contracts/proxies/SafeProxyFactory.sol#L52) function. 

This requires that a `saltNonce` is passed in and currently in the PR, if advanced parameters are not specified, the `saltNonce` is set to 0. I think that this should be changed and can be a bit of a footgun if a user calls `_setupSafe()` multiple times without specifying the `salt`, an outcome other than what the user probably expected would occur. 

I figured I would open this PR and have a conversation here as to what might be the best change to make (whether requiring the user to pass in the `saltNonce`, dynamically generating the saltNonce without collision or something else).

### CODE REVIEW

**Comment by colinnielsen** [comment]
Thanks for opening this @0xKitsune, I will review and merge once we solve this other PR.

RE: your concern, I think it's reasonable to have the `SafeTestTools` contract store it's own counter (`safeInstanceCount`) which increments every safe instance created. 
The salt nonce could just be:
```solidity
keccak256(abi.encodePacked("SAFE_TEST_TOOLS", safeInstanceCount))
```
Thoughts?

**Comment by 0xKitsune** [comment]
This sounds like a good approach. While an edge case, there is a possibility for a user to initialize a new safe with `_setupSafe()` and then initialize another safe with advanced parameters, not realizing that they used the same salt. I would imagine this is unlikely to happen and good documentation will probably suffice. Let me know what you think.

**Comment by colinnielsen** [comment]
> This sounds like a good approach. While an edge case, there is a possibility for a user to initialize a new safe with `_setupSafe()` and then initialize another safe with advanced parameters, not realizing that they used the same salt. I would imagine this is unlikely to happen and good documentation will probably suffice. Let me know what you think.

Extremely unlikely, but I like your adversarial mindset :)

**Comment by colinnielsen** [comment]
@0xKitsune merging this in - thanks again.
Next time, make sure to not commit any code formatted with your config of `forge fmt`. It was a pain to fix some stylistic merge conflicts

**Pull request merged**
